### ISSUE TITLE
TypeError: unexpected type, use Uint8Array

### ISSUE THREAD

**Issue by gtsonevv** [near/near-workspaces-js#236]
`TypeError: unexpected type, use Uint8Array` when I try to initialize a Worker in 'jsdom' environment with jest.

my code:
```
beforeAll(async () => {
    worker = await Worker.init();
});
```
jest.config.js:
```
module.exports = {
    preset: 'ts-jest',
    collectCoverage: true,
    testEnvironment: 'jsdom'
}
```
Error:
<img width="871" alt="Screenshot 2024-02-21 at 7 55 27" src="https://github.com/near/near-workspaces-js/assets/31661340/3c179943-5775-4a68-95f2-363c810d6f9a">

**Comment by gtsonevv** [comment]
There is a bugfix related to this bug in the latest version of near-api-js(3.0.2), updating the near-api-js dependency in near-workspaces-js could potentially fix this issue.

**Comment by gtsonevv** [comment]
It has been verified by our team, updating to the latest version of near-api-js will fix this issue.

**Comment by fospring** [comment]
@gtsonevv when I update near-api-js to v3.0.3,the ci task failed with `Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory`: https://github.com/near/near-workspaces-js/actions/runs/8159537274/job/22304059459?pr=238. Is there any changes in `near-api-js` will increase the memory usage?

**Comment by gtsonevv** [comment]
Hey @fospring,
```
borsh.deserialize(schema, StatusMessage, data);
```
and 
```
borsh.serialize(schema, statusMessage);
```
from `02.patch-state.ava.ts` seem to be causing this issue but I'm still not sure why.

**Comment by fospring** [comment]
Hey @gtsonevv, it seems no for this reason, I just skipped this test
